# Generated by Django 3.1.3 on 2020-11-08 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvestigAnimalesApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='especie',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
